Repository assurance-maladie-digital/design-system-v3, pull requests merged in 2025-08, with the labels that each got.

#828 HeaderBar/HeaderBurgerMenu correction post audit
  .storybook/public/audits/HeaderBar.xlsx
  .storybook/public/audits/HeaderBurgerMenu.xlsx
  src/components/HeaderBar/Accessibilite.stories.ts
  src/components/HeaderBar/HeaderBar.stories.ts
  src/components/HeaderBar/HeaderBar.vue
  src/components/HeaderBar/HeaderBurgerMenu/Accessibilite.stories.ts
  src/components/HeaderBar/HeaderBurgerMenu/HeaderBurgerMenu.stories.ts
  src/components/HeaderBar/HeaderBurgerMenu/HeaderBurgerMenu.vue
  src/components/HeaderBar/HeaderBurgerMenu/HeaderMenuItem/HeaderMenuItem.vue
  src/components/HeaderBar/HeaderBurgerMenu/HeaderMenuSection/HeaderMenuSection.vue
  src/components/HeaderBar/HeaderBurgerMenu/HeaderMenuSection/tests/HeaderMenuSection.spec.ts
  src/components/HeaderBar/HeaderBurgerMenu/HeaderSubMenu/HeaderSubMenu.stories.ts
  src/components/HeaderBar/HeaderBurgerMenu/HeaderSubMenu/HeaderSubMenu.vue
  src/components/HeaderBar/HeaderBurgerMenu/locals.ts
  src/components/HeaderBar/HeaderBurgerMenu/tests/HeaderBurgerMenu.spec.ts
  src/components/HeaderBar/HeaderBurgerMenu/tests/__snapshots__/HeaderBurgerMenu.spec.ts.snap
  src/components/HeaderBar/HeaderBurgerMenu/useMenuPosition.ts
  src/components/HeaderBar/HeaderLogo/HeaderLogo.vue
  src/components/HeaderBar/HeaderMenuBtn/HeaderMenuBtn.vue
  src/components/HeaderBar/locales.ts
  src/components/HeaderBar/tests/__snapshots__/HeaderBar.spec.ts.snap
  src/directives/lockFocus.ts
Labels: accessibility

#858 DataList at DataListGroup fixs post audit rgaa
  .storybook/public/audits/DataList.xlsx
  .storybook/public/audits/DataListGroup.xlsx
  src/components/DataList/Accessibilite.stories.ts
  src/components/DataList/DataList.vue
  src/components/DataListGroup/Accessibilite.stories.ts
  src/components/DataListGroup/DataListGroup.vue
  src/components/DataListItem/DataListItem.vue
  src/components/DataListItem/config.ts
  src/components/DataListItem/tests/DataListItem.spec.ts
  src/components/HeaderLoading/HeaderLoading.vue
Labels: accessibility

#977 Feat/add form validation guide
  dev/Playground.vue
  src/components/Customs/Selects/SelectOverview.mdx
  src/components/Customs/SyCheckbox/SyCheckbox.mdx
  src/components/Customs/SyTextField/SyTextField.mdx
  src/components/Customs/SyTextField/SyTextField.vue
  src/components/DatePicker/DatePickerValidationExample/DatePickerValidation.mdx
  src/components/NirField/NirField.mdx
  src/components/PasswordField/PasswordField.mdx
  src/components/PeriodField/PeriodField.mdx
  src/components/PhoneField/PhoneField.mdx
  src/stories/GuideDuDev/FormValidationGuide.mdx
Labels: documentation

#994 improve header navigation bar after audit and add SyTabs
  .storybook/public/audits/HeaderNavigationBar.xlsx
  src/components/Customs/SyTabs/Accessibilite.mdx
  src/components/Customs/SyTabs/SyTabs.mdx
  src/components/Customs/SyTabs/SyTabs.stories.ts
  src/components/Customs/SyTabs/SyTabs.vue
  src/components/Customs/SyTabs/config.ts
  src/components/Customs/SyTabs/tests/SyTabs.spec.ts
  src/components/Customs/SyTabs/types.ts
  src/components/HeaderNavigationBar/HorizontalNavbar/HorizontalNavbar.vue
  src/components/HeaderNavigationBar/tests/HeaderNavigationBar.spec.ts
Labels: accessibility

#1023 Feat/added a check on tab change
  src/components/Customs/SyTabs/Accessibilite.mdx
  src/components/Customs/SyTabs/SyTabs.stories.ts
  src/components/Customs/SyTabs/SyTabs.vue
  src/components/Customs/SyTabs/types.ts
  src/components/HeaderNavigationBar/HeaderNavigationBar.mdx
  src/components/HeaderNavigationBar/HeaderNavigationBar.stories.ts
  src/components/HeaderNavigationBar/HeaderNavigationBar.vue
  src/components/HeaderNavigationBar/HorizontalNavbar/HorizontalNavbar.vue
Labels: enhancement
