Repository assurance-maladie-digital/design-system-v3, pull requests merged in 2025-04, with the labels that each got.

#540 Fix/improve dp doc
  src/components/DatePicker/DatePickerValidation.mdx
  src/components/DatePicker/DatePickerValidation.stories.ts
  src/components/DatePicker/DatePickerValidationExamples.vue
  src/composables/rules/useFieldValidation.ts
Labels: documentation

#545 PhoneField: display default countryCode
  src/components/PhoneField/PhoneField.stories.ts
  src/components/PhoneField/PhoneField.vue
  src/components/PhoneField/tests/PhoneField.spec.ts
  src/components/index.ts
Labels: bug, documentation

#555 SkipLink - fix d audit d accessibilité
  .storybook/public/audits/SkipLink.xlsx
  src/components/SkipLink/Accessibilite.stories.ts
  src/components/SkipLink/SkipLink.vue
  src/components/SkipLink/tests/__snapshots__/skipLink.spec.ts.snap
  src/components/SkipLink/tests/skipLink.spec.ts
Labels: help wanted, accessibility

#544 SyAlert - fix d'audit d'accessibilité
  .storybook/public/audits/Alert.xlsx
  src/components/SyAlert/Accessibilite.stories.ts
  src/components/SyAlert/SyAlert.mdx
  src/components/SyAlert/SyAlert.stories.ts
  src/components/SyAlert/SyAlert.vue
  src/components/SyAlert/tests/SyAlert.spec.ts
  src/components/SyAlert/tests/__snapshots__/SyAlert.spec.ts.snap
Labels: help wanted, accessibility
