Repository assurance-maladie-digital/design-system-v3, pull requests merged in 2025-07, with the labels that each got.

#731 Feat/add holiday on date picker
  src/components/DatePicker/ComplexDatePicker/ComplexDatePicker.stories.ts
  src/components/DatePicker/ComplexDatePicker/ComplexDatePicker.vue
  src/components/DatePicker/DatePicker/DatePicker.stories.ts
  src/components/DatePicker/DatePicker/DatePicker.vue
  src/components/DatePicker/DatePicker/tests/DatePicker.events.spec.ts
  src/components/DatePicker/DatePicker/tests/DatePicker.spec.ts
  src/components/DatePicker/DateTextInput/NoCalendar.stories.ts
  src/components/DatePicker/composables/index.ts
  src/components/DatePicker/composables/useAsteriskDisplay.ts
  src/components/PeriodField/PeriodField.vue
Labels: PAG

#749 fix handleBlur in dateTextInput
  src/components/DatePicker/DateTextInput/DateTextInput.vue
Labels: bug

#772 improve access on datePicker
  src/components/DatePicker/DatePicker/DatePicker.vue
  src/components/DatePicker/composables/useMonthButtonCustomization.ts
  src/composables/date/useDatePickerAccessibility.ts
Labels: accessibility

#768 Feat/add sy icon
  dev/CustomPlaygrounds/SyIcon.vue
  src/components/Customs/SyIcon/Accessibilite.mdx
  src/components/Customs/SyIcon/Accessibilite.stories.ts
  src/components/Customs/SyIcon/SyIcon.mdx
  src/components/Customs/SyIcon/SyIcon.spec.ts
  src/components/Customs/SyIcon/SyIcon.stories.ts
  src/components/Customs/SyIcon/SyIcon.vue
  src/components/Customs/SyIcon/SyIconAccessibility.vue
  src/components/Customs/SyIcon/utils/iconUtils.ts
  src/components/Customs/SySelect/SySelect.vue
  src/components/index.ts
  src/directives/rgaaSvgFix.ts
  src/stories/Accessibilite/Avancement/Avancement.stories.ts
  src/stories/Accessibilite/Vuetify/VuetifyItems.ts
  src/stories/Directives/SvgDirective.mdx
Labels: enhancement, accessibility

#796 ContextualMenu audit rgaa
  .storybook/public/audits/ContextualMenu.xlsx
  src/components/ContextualMenu/Accessibilite.stories.ts
  src/components/ContextualMenu/ContextualMenu.stories.ts
  src/components/ContextualMenu/ContextualMenu.vue
  src/components/ContextualMenu/DeepMenu.vue
  src/components/ContextualMenu/tests/ContextualMenu.spec.ts
  src/components/ContextualMenu/tests/__snapshots__/ContextualMenu.spec.ts.snap
  src/components/ContextualMenu/types.ts
Labels: accessibility

#840 fix issue #793
  src/components/NirField/NirField.vue
Labels: bug

#815 fix footerBar after audit
  .storybook/public/audits/FooterBar.xlsx
  src/components/FooterBar/Accessibilite.stories.ts
  src/components/FooterBar/FooterBar.vue
  src/components/FooterBar/tests/__snapshots__/FooterBar.spec.ts.snap
Labels: accessibility

#848 improve avancement page
  src/stories/Accessibilite/Avancement/Avancement.mdx
  src/stories/Accessibilite/Avancement/Avancement.stories.ts
Labels: documentation
